### ISSUE TITLE
Move from unfree dependencies

### ISSUE THREAD

**Issue by hatch01** [Toporin/Seedkeeper-Tool#14]
The library PySimpleGUIQt does not have a free license.
It would be very great to move to another GUI lib to have a fully free software.
Moreover, PySimpleGUIQt is hard to package for nix due to some rsa key verification, and it would probably be a lot easier with other libs.

**Comment by Toporin** [comment]
We are working on a completely new version of Seedkeeper-Tool for desktop (as well as mobile apps). The new version will be based on TKinter (same as for the new [satochip-util app](https://github.com/Toporin/Satochip-Utils) ) and should be available in beta starting in September!

**Comment by hatch01** [comment]
Oh, I love this kind of news!
Would love to package it quickly when the beta comes!
